version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://api:5000
    depends_on:
      - api
